"""
Basic tests for pygcode_viewer
"""

import os
import sys
import tempfile
import pytest

# Add parent directory to path for development testing
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


def test_import():
    """Test that the module can be imported."""
    import pygcode_viewer
    assert hasattr(pygcode_viewer, 'GCodeViewer')
    assert hasattr(pygcode_viewer, 'CameraParams')
    assert hasattr(pygcode_viewer, 'ViewConfig')


def test_version():
    """Test that version is defined."""
    import pygcode_viewer
    assert pygcode_viewer.__version__ == "0.1.0"


def test_camera_params():
    """Test CameraParams dataclass."""
    from pygcode_viewer import CameraParams
    
    # Default values
    cam = CameraParams()
    assert cam.position == (100.0, 100.0, 100.0)
    assert cam.target == (0.0, 0.0, 50.0)
    assert cam.up == (0.0, 0.0, 1.0)
    assert cam.fov == 45.0
    
    # Custom values
    cam = CameraParams(
        position=(200, 200, 200),
        target=(50, 50, 25),
        fov=60.0
    )
    assert cam.position == (200, 200, 200)
    assert cam.target == (50, 50, 25)
    assert cam.fov == 60.0


def test_view_config():
    """Test ViewConfig dataclass."""
    from pygcode_viewer import ViewConfig
    
    config = ViewConfig()
    assert config.view_type == "FeatureType"
    assert config.width == 1920
    assert config.height == 1080
    
    # Test to_dict
    d = config.to_dict()
    assert d["view_type"] == "FeatureType"
    assert d["output"]["width"] == 1920
    
    # Test from_dict
    config2 = ViewConfig.from_dict({
        "view_type": "Speed",
        "output": {"width": 1280, "height": 720}
    })
    assert config2.view_type == "Speed"
    assert config2.width == 1280
    assert config2.height == 720


def test_view_config_json():
    """Test ViewConfig JSON serialization."""
    from pygcode_viewer import ViewConfig
    import json
    
    config = ViewConfig()
    config.view_type = "Height"
    config.layer_range = (0, 50)
    
    json_str = config.to_json()
    parsed = json.loads(json_str)
    
    assert parsed["view_type"] == "Height"
    assert parsed["layer_range"] == [0, 50]
    
    # Round-trip
    config2 = ViewConfig.from_json(json_str)
    assert config2.view_type == "Height"
    assert config2.layer_range == (0, 50)


# Skip tests that require the C++ extension if not built
try:
    from pygcode_viewer import _pygcode_viewer
    HAS_EXTENSION = True
except ImportError:
    HAS_EXTENSION = False


@pytest.mark.skipif(not HAS_EXTENSION, reason="C++ extension not built")
def test_viewer_core_creation():
    """Test GCodeViewerCore creation."""
    from pygcode_viewer import _pygcode_viewer
    
    viewer = _pygcode_viewer.GCodeViewerCore()
    assert not viewer.is_loaded()


@pytest.mark.skipif(not HAS_EXTENSION, reason="C++ extension not built")
def test_viewer_creation():
    """Test GCodeViewer creation."""
    from pygcode_viewer import GCodeViewer
    
    viewer = GCodeViewer()
    assert viewer.get_layer_count() == 0
    assert viewer.get_bounding_box() == (0, 0, 0, 0, 0, 0)


# Sample GCODE for testing
SAMPLE_GCODE = """; Generated by PrusaSlicer
; LAYER_CHANGE
; Z:0.2
G28 ; home
G1 Z0.2 F1000
M104 S200
M109 S200
;TYPE:Skirt
G1 X10 Y10 F3000
G1 X100 Y10 E10 F1500
G1 X100 Y100 E20
G1 X10 Y100 E30
G1 X10 Y10 E40
; LAYER_CHANGE
; Z:0.4
G1 Z0.4
;TYPE:Perimeter
G1 X20 Y20 E41
G1 X90 Y20 E50
G1 X90 Y90 E59
G1 X20 Y90 E68
G1 X20 Y20 E77
; LAYER_CHANGE
; Z:0.6
G1 Z0.6
;TYPE:Internal infill
G1 X30 Y30 E78
G1 X80 Y80 E90
"""


@pytest.mark.skipif(not HAS_EXTENSION, reason="C++ extension not built")
def test_load_gcode():
    """Test loading GCODE file."""
    from pygcode_viewer import GCodeViewer
    
    # Create temporary GCODE file
    with tempfile.NamedTemporaryFile(mode='w', suffix='.gcode', delete=False) as f:
        f.write(SAMPLE_GCODE)
        gcode_path = f.name
    
    try:
        viewer = GCodeViewer()
        viewer.load(gcode_path)
        
        # Check that data was loaded
        assert viewer.get_layer_count() > 0
        
        bbox = viewer.get_bounding_box()
        # Should have non-zero bounding box
        assert bbox[3] > bbox[0]  # max_x > min_x
        assert bbox[4] > bbox[1]  # max_y > min_y
        
    finally:
        os.unlink(gcode_path)


@pytest.mark.skipif(not HAS_EXTENSION, reason="C++ extension not built")
def test_render_to_file():
    """Test rendering GCODE to PNG file."""
    from pygcode_viewer import GCodeViewer
    
    # Create temporary GCODE file
    with tempfile.NamedTemporaryFile(mode='w', suffix='.gcode', delete=False) as f:
        f.write(SAMPLE_GCODE)
        gcode_path = f.name
    
    output_path = tempfile.mktemp(suffix='.png')
    
    try:
        viewer = GCodeViewer()
        viewer.load(gcode_path)
        viewer.set_camera(pos=(100, 100, 100), target=(50, 50, 0.5))
        viewer.render_to_file(output_path, width=640, height=480)
        
        # Check that output file was created
        assert os.path.exists(output_path)
        assert os.path.getsize(output_path) > 0
        
        # Verify it's a valid PNG (check magic number)
        with open(output_path, 'rb') as f:
            header = f.read(8)
            assert header[:4] == b'\x89PNG'
            
    finally:
        os.unlink(gcode_path)
        if os.path.exists(output_path):
            os.unlink(output_path)


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
